Add sample dotnet invocation to some .githooks

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,3 +1,10 @@
 #!/bin/sh
+command -v dotnet >/dev/null 2>&1 || { echo >&2 "\ndotnet was not found on your path. Install the .Net SDK first.\n"; exit 2; }
+dotnet Relative/Path/To/Hook/Assembly.dll pre-push "$@"
+ret=$?
+if [ $ret -ne 0 ]; then
+    exit $ret
+fi
+
 command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.\n"; exit 2; }
 git lfs pre-push "$@"
